#!/usr/bin/env bash
set -euo pipefail

# Generate the mined assets consumed by the EEST deep-branches benchmark.
#
# Why this script exists:
# - `../execution-specs/tests/benchmark/stateful/bloatnet/depth_benchmarks`
#   expects files named `depth_<storage_depth>.sol`, `depth_<storage_depth>.bin`,
#   and `s<storage_depth>_acc<account_depth>.json`.
# - The current `worst_case_miner` CLI no longer has the older one-shot
#   `--storage-depth/--account-depth` interface. Instead, it exposes a single
#   `--depth` flag plus optional CREATE2 mining flags.
# - Because of that, regenerating the EEST assets now requires a two-pass flow:
#   1. Mine a storage-depth-specific contract and capture its `storage_keys`.
#   2. Reuse that generated Solidity contract to mine each account-depth JSON.
#   3. Merge the 32-byte `storage_keys` from step 1 back into each JSON file.
#      This is necessary because the current `--init-code <path>.sol` code path
#      recompiles the contract but intentionally leaves `storage_keys` empty.
#
# Default behavior:
# - Rebuild the full EEST matrix into `./mined_assets`:
#   - `depth_10.{sol,bin}` and `s10_acc{3,4,5,6,7}.json`
#   - `depth_11.{sol,bin}` and `s11_acc{3,4,5,6,7}.json`
#   - `depth_12.{sol,bin}` and `s12_acc{3,4,5}.json`
# - Use Nick's deterministic deployer at:
#   `0x4e59b44847b379578588920ca78fbf26c0b4956c`
# - Use `num_contracts=18000`, matching the checked-in benchmark assets.
#
# Requirements:
# - `cargo`
# - `jq`
# - `solc 0.8.30`
# - a successful `cargo build --release` for this repo
#
# Examples:
#   ./generate_eest_assets.sh
#   ./generate_eest_assets.sh --case 3:2 --num-contracts 5 --out-dir /tmp/eest-sanity
#   ./generate_eest_assets.sh --skip-build --threads 32

readonly ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly DEFAULT_DEPLOYER="0x4e59b44847b379578588920ca78fbf26c0b4956c"
readonly REQUIRED_SOLC_PREFIX="0.8.30+"
readonly -a DEFAULT_CASE_SPECS=(
  "10:3,4,5,6,7"
  "11:3,4,5,6,7"
  "12:3,4,5"
)

usage() {
  cat <<'EOF'
Generate the mined assets consumed by the EEST deep-branches benchmark.

By default this rebuilds the current benchmark matrix into `./mined_assets`.
If one or more `--case` flags are provided, they replace the default matrix.

Usage:
  ./generate_eest_assets.sh [options]

Options:
  --case <storage_depth:acc1,acc2,...>
      Generate one storage-depth case and the listed account-depth JSON files.
      May be passed multiple times.
      Example: --case 10:3,4,5,6,7

  --num-contracts <N>
      Number of mined CREATE2 contracts in each JSON file.
      Default: 18000

  --threads <N>
      Number of mining threads to use.
      Default: detected CPU count

  --deployer <0x...>
      CREATE2 deployer address.
      Default: Nick's deterministic deployer

  --out-dir <PATH>
      Output directory for `depth_*.sol`, `depth_*.bin`, and `s*_acc*.json`.
      Default: ./mined_assets

  --bin-path <PATH>
      Path to the `worst_case_miner` binary to use.
      Default: ./target/release/worst_case_miner

  --skip-build
      Do not run `cargo build --release` before mining.

  --keep-temp
      Keep the temporary working directory instead of deleting it on exit.

  --allow-other-solc
      Skip the exact `solc 0.8.30` version check.
      This is not recommended for reproducible assets because the compiler
      version affects the generated bytecode and CREATE2 init code hash.

  -h, --help
      Show this help message and exit.
EOF
}

log() {
  printf '[generate_eest_assets] %s\n' "$*"
}

die() {
  printf '[generate_eest_assets] error: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

detect_threads() {
  if command -v nproc >/dev/null 2>&1; then
    nproc
    return
  fi
  if command -v getconf >/dev/null 2>&1; then
    getconf _NPROCESSORS_ONLN
    return
  fi
  printf '1\n'
}

resolve_path() {
  local path="$1"
  local base_dir="$2"

  if [[ "$path" == /* ]]; then
    printf '%s\n' "$path"
  else
    printf '%s/%s\n' "$base_dir" "$path"
  fi
}

validate_positive_integer() {
  local value="$1"
  local name="$2"

  [[ "$value" =~ ^[0-9]+$ ]] || die "$name must be a non-negative integer: $value"
  [[ "$value" != "0" ]] || die "$name must be greater than zero"
}

validate_case_spec() {
  local case_spec="$1"
  local storage_depth
  local account_depths_csv

  [[ "$case_spec" == *:* ]] || die "invalid --case format: $case_spec"
  storage_depth="${case_spec%%:*}"
  account_depths_csv="${case_spec#*:}"

  validate_positive_integer "$storage_depth" "storage depth"
  [[ -n "$account_depths_csv" ]] || die "missing account depths in --case: $case_spec"
  [[ "$account_depths_csv" =~ ^[0-9]+(,[0-9]+)*$ ]] || die "invalid account depth list in --case: $case_spec"
}

run_miner() {
  local description="$1"
  shift

  log "$description"
  (
    cd "$WORK_DIR"
    "$BIN_PATH" "$@"
  )
}

CALLER_PWD="$(pwd)"
OUT_DIR="$ROOT_DIR/mined_assets"
BIN_PATH="$ROOT_DIR/target/release/worst_case_miner"
THREADS="$(detect_threads)"
NUM_CONTRACTS=18000
DEPLOYER="$DEFAULT_DEPLOYER"
SKIP_BUILD=0
KEEP_TEMP=0
ALLOW_OTHER_SOLC=0
CUSTOM_CASES=0
declare -a CASE_SPECS=()

while (($# > 0)); do
  case "$1" in
    --case)
      (($# >= 2)) || die "missing value for $1"
      validate_case_spec "$2"
      CASE_SPECS+=("$2")
      CUSTOM_CASES=1
      shift 2
      ;;
    --num-contracts)
      (($# >= 2)) || die "missing value for $1"
      NUM_CONTRACTS="$2"
      shift 2
      ;;
    --threads)
      (($# >= 2)) || die "missing value for $1"
      THREADS="$2"
      shift 2
      ;;
    --deployer)
      (($# >= 2)) || die "missing value for $1"
      DEPLOYER="$2"
      shift 2
      ;;
    --out-dir)
      (($# >= 2)) || die "missing value for $1"
      OUT_DIR="$2"
      shift 2
      ;;
    --bin-path)
      (($# >= 2)) || die "missing value for $1"
      BIN_PATH="$2"
      shift 2
      ;;
    --skip-build)
      SKIP_BUILD=1
      shift
      ;;
    --keep-temp)
      KEEP_TEMP=1
      shift
      ;;
    --allow-other-solc)
      ALLOW_OTHER_SOLC=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

validate_positive_integer "$NUM_CONTRACTS" "num-contracts"
validate_positive_integer "$THREADS" "threads"
[[ "$DEPLOYER" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "deployer must be a 20-byte hex address: $DEPLOYER"

if ((CUSTOM_CASES == 0)); then
  CASE_SPECS=("${DEFAULT_CASE_SPECS[@]}")
fi

OUT_DIR="$(resolve_path "$OUT_DIR" "$CALLER_PWD")"
BIN_PATH="$(resolve_path "$BIN_PATH" "$CALLER_PWD")"

require_cmd cargo
require_cmd jq
require_cmd solc

if ((SKIP_BUILD == 0)); then
  log "Building release binary"
  (
    cd "$ROOT_DIR"
    cargo build --release
  )
fi

[[ -x "$BIN_PATH" ]] || die "miner binary not found or not executable: $BIN_PATH"

solc_version="$(solc --version | awk '/^Version: /{print $2}')"
if ((ALLOW_OTHER_SOLC == 0)) && [[ "$solc_version" != ${REQUIRED_SOLC_PREFIX}* ]]; then
  die "expected solc ${REQUIRED_SOLC_PREFIX%+}.x for reproducible assets, found: $solc_version"
fi

TMP_DIR="$(mktemp -d -t generate-eest-assets.XXXXXX)"
WORK_DIR="$TMP_DIR/work"
mkdir -p "$WORK_DIR" "$OUT_DIR"

cleanup() {
  if ((KEEP_TEMP == 1)); then
    log "Keeping temporary directory: $TMP_DIR"
  else
    rm -rf "$TMP_DIR"
  fi
}
trap cleanup EXIT

log "Using repo root: $ROOT_DIR"
log "Using miner binary: $BIN_PATH"
log "Using solc version: $solc_version"
log "Writing assets to: $OUT_DIR"
log "Using threads: $THREADS"
log "Using num_contracts: $NUM_CONTRACTS"

for case_spec in "${CASE_SPECS[@]}"; do
  storage_depth="${case_spec%%:*}"
  account_depths_csv="${case_spec#*:}"
  IFS=',' read -r -a account_depths <<<"$account_depths_csv"

  validate_positive_integer "$storage_depth" "storage depth"
  for account_depth in "${account_depths[@]}"; do
    validate_positive_integer "$account_depth" "account depth"
  done

  seed_json="$TMP_DIR/s${storage_depth}_seed.json"
  depth_sol="$OUT_DIR/depth_${storage_depth}.sol"
  depth_bin="$OUT_DIR/depth_${storage_depth}.bin"

  log "Generating storage-depth contract for depth $storage_depth"
  run_miner \
    "Mining storage seed for depth $storage_depth" \
    --depth "$storage_depth" \
    --threads "$THREADS" \
    --deployer "$DEPLOYER" \
    --num-contracts 1 \
    --accounts-output "$seed_json"

  [[ -f "$WORK_DIR/contracts/WorstCaseERC20.sol" ]] || die "expected generated contract not found for storage depth $storage_depth"
  cp "$WORK_DIR/contracts/WorstCaseERC20.sol" "$depth_sol"
  jq -r '.init_code | ltrimstr("0x")' "$seed_json" >"$depth_bin"

  seed_storage_key_count="$(jq '.storage_keys | length' "$seed_json")"
  [[ "$seed_storage_key_count" == "$storage_depth" ]] || die "seed storage key count mismatch for depth $storage_depth: expected $storage_depth, got $seed_storage_key_count"

  for account_depth in "${account_depths[@]}"; do
    out_json="$OUT_DIR/s${storage_depth}_acc${account_depth}.json"
    merged_json="$TMP_DIR/merged_s${storage_depth}_acc${account_depth}.json"

    run_miner \
      "Mining account-depth JSON for storage depth $storage_depth / account depth $account_depth" \
      --depth "$account_depth" \
      --threads "$THREADS" \
      --deployer "$DEPLOYER" \
      --num-contracts "$NUM_CONTRACTS" \
      --init-code "$depth_sol" \
      --accounts-output "$out_json"

    jq --slurpfile seed "$seed_json" \
      '.storage_keys = $seed[0].storage_keys' \
      "$out_json" >"$merged_json"
    mv "$merged_json" "$out_json"

    actual_storage_keys="$(jq '.storage_keys | length' "$out_json")"
    actual_target_depth="$(jq '.target_depth' "$out_json")"
    actual_num_contracts="$(jq '.num_contracts' "$out_json")"
    actual_contracts_len="$(jq '.contracts | length' "$out_json")"
    actual_aux_len="$(jq '.contracts[0].auxiliary_accounts | length' "$out_json")"

    [[ "$actual_storage_keys" == "$storage_depth" ]] || die "storage_keys length mismatch in $out_json: expected $storage_depth, got $actual_storage_keys"
    [[ "$actual_target_depth" == "$account_depth" ]] || die "target_depth mismatch in $out_json: expected $account_depth, got $actual_target_depth"
    [[ "$actual_num_contracts" == "$NUM_CONTRACTS" ]] || die "num_contracts mismatch in $out_json: expected $NUM_CONTRACTS, got $actual_num_contracts"
    [[ "$actual_contracts_len" == "$NUM_CONTRACTS" ]] || die "contracts array length mismatch in $out_json: expected $NUM_CONTRACTS, got $actual_contracts_len"
    [[ "$actual_aux_len" == "$account_depth" ]] || die "auxiliary_accounts length mismatch in $out_json: expected $account_depth, got $actual_aux_len"

    log "Wrote $out_json"
  done

  log "Wrote $depth_sol"
  log "Wrote $depth_bin"
done

log "Asset generation complete"
